import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "../../packages/ui/src/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "var(--background)",
        foreground: "hsl(var(--foreground))",
        brand: {
          50: "#f0f4ff",
          100: "#dbe4ff",
          200: "#bac8ff",
          300: "#91a7ff",
          400: "#748ffc",
          500: "#5c7cfa",
          600: "#4c6ef5",
          700: "#4263eb",
          800: "#3b5bdb",
          900: "#364fc7",
        },
        // Stitch generated colors
        "surface-container-highest": "#2d3449",
        "surface-tint": "#c3c0ff",
        "primary-container": "#635bff",
        "outline-variant": "#464555",
        "on-secondary-fixed-variant": "#434172",
        "tertiary-container": "#716ea3",
        "surface-glass": "rgba(30, 27, 75, 0.7)",
        "on-tertiary-fixed-variant": "#444173",
        "primary-fixed": "#e2dfff",
        "on-primary-container": "#fefaff",
        "on-surface": "#dbe2fd",
        "tertiary-fixed-dim": "#c4c1fb",
        "text-muted": "#94A3B8",
        "inverse-surface": "#dbe2fd",
        "inverse-on-surface": "#283044",
        "error": "#ffb4ab",
        "success-vibrant": "#10B981",
        "secondary": "#c4c1fb",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-fixed": "#181445",
        "on-primary-fixed-variant": "#321ed2",
        "tertiary": "#c4c1fb",
        "on-secondary": "#2c2b5a",
        "on-primary-fixed": "#0f0069",
        "surface": "#0b1326",
        "outline": "#918fa1",
        "surface-container-low": "#131b2e",
        "on-secondary-fixed": "#171544",
        "on-tertiary-container": "#fefaff",
        "tertiary-fixed": "#e3dfff",
        "on-primary": "#1d00a5",
        "inverse-primary": "#4c42e9",
        "surface-variant": "#2d3449",
        "primary": "#c3c0ff",
        "secondary-container": "#454475",
        "surface-dim": "#0b1326",
        "on-tertiary": "#2d2a5b",
        "on-secondary-container": "#b6b3ec",
        "surface-container-lowest": "#060d20",
        "secondary-fixed-dim": "#c4c1fb",
        "on-background": "#dbe2fd",
        "surface-container-high": "#222a3e",
        "on-surface-variant": "#c7c4d8",
        "secondary-fixed": "#e3dfff",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "glass-border": "rgba(255, 255, 255, 0.08)",
        "error-container": "#93000a",
        "surface-bright": "#31394e",
        "surface-container": "#171f33"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "Inter", "system-ui", "sans-serif"],
        display: ["'Clash Display'", "system-ui", "sans-serif"],
        "body-md": ["Inter"],
        "headline-lg": ["Outfit"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Outfit"],
        "display-xl": ["Outfit"],
        "headline-lg-mobile": ["Outfit"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }]
      },
      spacing: {
        "base": "4px",
        "md": "24px",
        "container-max": "1280px",
        "gutter": "24px",
        "lg": "40px",
        "xs": "8px",
        "xl": "64px",
        "sm": "16px"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
